const data ={
    product:[
        {
            _id:'1',
            name:'Wedding Lehnga',
            category:'Lehnga',
            image:'/images/pic-7.jpg',
            price:3000,
            brand:'Manyavar',
            rating:'5',
            numReview:10,
            description:'High quality product',
        },
        {
            _id:'2',
            name:'Mehroon BridalLehnga',
            category:'Lehnga',
            image:'/images/pic-4.jpg',
            price:4000,
            brand:'Manyavar',
            rating:'4.2',
            numReview:13,
            description:'High quality product',
        },
        {
            _id:'3',
            name:'Wedding Lehnga',
            category:'Lehnga',
            image:'/images/p1.jpg',
            price:3000,
            brand:'Manyavar',
            rating:'5',
            numReview:17,
            description:'High quality product',
        },
        {
            _id:'4',
            name:'Mehroon Bridal Lehnga',
            category:'Lehnga',
            image:'/images/pic-1.jpg',
            price:4000,
            brand:'Manyavar',
            rating:'3.5',
            numReview:18,
            description:'High quality product',
        },
        {
            _id:'5',
            name:'Wedding Lehnga',
            category:'Lehnga',
            image:'/images/pic-10.jpg',
            price:3000,
            brand:'Manyavar',
            rating:'3.9',
            numReview:14,
            description:'High quality product',
        },
        {
            _id:'6',
            name:'Mehroon Bridal Lehnga',
            category:'Lehnga',
            image:'/images/pic-2.jpg',
            price:4000,
            brand:'Manyavar',
            rating:'4',
            numReview:10,
            description:'High quality product',
        },
        {
            _id:'7',
            name:'Mehroon Bridal Lehnga',
            category:'Lehnga',
            image:'/images/pic-10.jpg',
            price:4000,
            brand:'Manyavar',
            rating:'4.5',
            numReview:10,
            description:'High quality product',
        },
    ]
}
export default data;